{{- if .Values.buckets }}
apiVersion: batch/v1
kind: Job
metadata:
  name: minio-post-job
  labels:
    app: minio
  annotations:
    {{- toYaml $.Values.annotations | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        app: minio
      annotations:
        {{- toYaml $.Values.annotations | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      volumes:
        - name: etc-path
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: minio-configuration
          projected:
            sources:
              - configMap:
                  name: minio
              - secret:
                  name: minio-secret
      containers:
        - name: minio-make-bucket
          image: "{{ .Values.mcImage.repository }}:{{ .Values.mcImage.tag }}"
          imagePullPolicy: {{ .Values.mcImage.pullPolicy }}
          command: [ "/bin/sh", "/config/initialize" ]
          env:
            - name: MINIO_ENDPOINT
              value: minio
            - name: MINIO_PORT
              value: {{ .Values.minioAPIPort }}
          volumeMounts:
            - name: etc-path
              mountPath: /etc/minio/mc
            - name: tmp
              mountPath: /tmp
            - name: minio-configuration
              mountPath: /config
{{- end }}
