---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: {{ .Release.Namespace }}
  labels:
    app: minio
  annotations:
    {{- toYaml $.Values.annotations | nindent 4 }}
spec:
  ports:
    - name: http-minio-api
      port: {{ .Values.minioAPIPort }}
      targetPort: {{ .Values.minioAPIPort }}
      protocol: TCP
    - name: http-minio-console
      port: {{ .Values.minioConsolePort }}
      targetPort: {{ .Values.minioConsolePort }}
      protocol: TCP
  selector:
    app: minio
